# Generated by Django 3.2.14 on 2022-07-12 16:47

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('deleted_by_cascade', models.BooleanField(default=False, editable=False)),
                ('content', models.TextField()),
                ('highlighted', models.TextField(blank=True, editable=False)),
                ('size', models.IntegerField()),
                ('title', models.CharField(blank=True, max_length=160)),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('lexer', models.CharField(editable=False, max_length=60)),
                ('expire', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(editable=False, max_length=255, unique=True)),
                ('view_count', models.PositiveIntegerField(default=0)),
                ('is_dmca', models.BooleanField(default=False)),
                ('is_removed', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Paste',
                'verbose_name_plural': 'Pastes',
                'ordering': ['-publish'],
                'managed': True,
            },
        ),
        migrations.AddIndex(
            model_name='paste',
            index=django.contrib.postgres.indexes.BTreeIndex(fields=['slug'], name='slug_idx'),
        ),
    ]
